export const MARKET_SIGNALS = [
    {
        "id": "sig_2000",
        "asset_symbol": "MSFT",
        "asset_name": "Microsoft",
        "description": "Microsoft is a global enterprise technology company focused on cloud computing, productivity software, enterprise infrastructure, and AI platforms.",
        "asset_type": "web2",
        "category": "Cloud",
        "raw_sentiment": 0.72,
        "fear_greed_score": 93,
        "confidence_score": 0.76,
        "trend_1h": -0.85,
        "trend_24h": -2.39,
        "trend_7d": -1.18,
        "price_usd": 906.79,
        "market_cap_usd": 513208278513,
        "pe_ratio": 64.63,
        "avg_volume_24h_usd": 1720788640,
        "topic": "Cloud",
        "is_high_confidence": true,
        "observed_at": "2025-12-29T10:41:00Z"
    },
    {
        "id": "sig_2001",
        "asset_symbol": "MSFT",
        "asset_name": "Microsoft",
        "description": "Microsoft is a global enterprise technology company focused on cloud computing, productivity software, enterprise infrastructure, and AI platforms.",
        "asset_type": "web2",
        "category": "Cloud",
        "raw_sentiment": 0.35,
        "fear_greed_score": 37,
        "confidence_score": 0.73,
        "trend_1h": 0.7,
        "trend_24h": -2.79,
        "trend_7d": 8.16,
        "price_usd": 786.62,
        "market_cap_usd": 2176481894190,
        "pe_ratio": 52.09,
        "avg_volume_24h_usd": 6313685568,
        "topic": "Margins",
        "is_high_confidence": true,
        "observed_at": "2026-01-10T22:22:00Z"
    },
    {
        "id": "sig_2002",
        "asset_symbol": "TSLA",
        "asset_name": "Tesla",
        "description": "Tesla is an electric vehicle and clean energy company focused on EV manufacturing, battery innovation, and autonomous driving technology.",
        "asset_type": "web2",
        "category": "EV",
        "raw_sentiment": 0.75,
        "fear_greed_score": 32,
        "confidence_score": 0.91,
        "trend_1h": -0.01,
        "trend_24h": 1.46,
        "trend_7d": -7.37,
        "price_usd": 293.58,
        "market_cap_usd": 3241617575078,
        "pe_ratio": 64.86,
        "avg_volume_24h_usd": 12990012920,
        "topic": "Margins",
        "is_high_confidence": false,
        "observed_at": "2026-01-29T19:49:00Z"
    },
    {
        "id": "sig_2003",
        "asset_symbol": "TSLA",
        "asset_name": "Tesla",
        "description": "Tesla is an electric vehicle and clean energy company focused on EV manufacturing, battery innovation, and autonomous driving technology.",
        "asset_type": "web2",
        "category": "EV",
        "raw_sentiment": -0.12,
        "fear_greed_score": 54,
        "confidence_score": 0.78,
        "trend_1h": 1.28,
        "trend_24h": -0.43,
        "trend_7d": -1.94,
        "price_usd": 564.47,
        "market_cap_usd": 2519575949799,
        "pe_ratio": 43.49,
        "avg_volume_24h_usd": 9499816919,
        "topic": "Cloud",
        "is_high_confidence": false,
        "observed_at": "2026-01-11T04:47:00Z"
    },
    {
        "id": "sig_2004",
        "asset_symbol": "AAPL",
        "asset_name": "Apple Inc",
        "description": "Apple Inc is a global consumer technology company generating revenue from hardware devices, digital services, and ecosystem subscriptions.",
        "asset_type": "web2",
        "category": "Tech",
        "raw_sentiment": 0.01,
        "fear_greed_score": 34,
        "confidence_score": 0.89,
        "trend_1h": 0.9,
        "trend_24h": 2.2,
        "trend_7d": 0.2,
        "price_usd": 640.47,
        "market_cap_usd": 3213592156258,
        "pe_ratio": 66.85,
        "avg_volume_24h_usd": 10318958542,
        "topic": "Innovation",
        "is_high_confidence": false,
        "observed_at": "2026-01-12T18:29:00Z"
    },
    {
        "id": "sig_2005",
        "asset_symbol": "AAPL",
        "asset_name": "Apple Inc",
        "description": "Apple Inc is a global consumer technology company generating revenue from hardware devices, digital services, and ecosystem subscriptions.",
        "asset_type": "web2",
        "category": "Tech",
        "raw_sentiment": -0.36,
        "fear_greed_score": 29,
        "confidence_score": 0.88,
        "trend_1h": -0.94,
        "trend_24h": 3.92,
        "trend_7d": 3.17,
        "price_usd": 96.32,
        "market_cap_usd": 1004764216082,
        "pe_ratio": 67.53,
        "avg_volume_24h_usd": 12238986528,
        "topic": "Revenue",
        "is_high_confidence": true,
        "observed_at": "2025-12-04T13:13:00Z"
    },
    {
        "id": "sig_1006",
        "asset_symbol": "UNI",
        "asset_name": "Uniswap",
        "description": "Uniswap is a decentralized exchange protocol enabling permissionless token swaps and automated liquidity provision on blockchain networks.",
        "asset_type": "web3",
        "category": "DeFi",
        "raw_sentiment": 0.53,
        "fear_greed_score": 8,
        "confidence_score": 0.91,
        "trend_1h": -0.76,
        "trend_24h": 6.11,
        "trend_7d": 16.16,
        "price_usd": 13013.32,
        "tvl_usd": 61681783552,
        "pool_volume_24h_usd": 25191397451,
        "onchain_tx_growth_24h": 3.8,
        "topic": "Liquidity",
        "is_high_confidence": false,
        "observed_at": "2026-01-19T21:36:00Z"
    },
    {
        "id": "sig_1007",
        "asset_symbol": "SOL",
        "asset_name": "Solana",
        "description": "Solana is a high performance Layer 1 blockchain optimized for fast transactions, low fees, and scalable decentralized applications.",
        "asset_type": "web3",
        "category": "L1",
        "raw_sentiment": -0.69,
        "fear_greed_score": 74,
        "confidence_score": 0.86,
        "trend_1h": 1.13,
        "trend_24h": -0.66,
        "trend_7d": 6.0,
        "price_usd": 19723.73,
        "tvl_usd": 55902572649,
        "pool_volume_24h_usd": 24830652024,
        "onchain_tx_growth_24h": 1.77,
        "topic": "Hype",
        "is_high_confidence": false,
        "observed_at": "2026-02-07T21:58:00Z"
    },
    {
        "id": "sig_2008",
        "asset_symbol": "NVDA",
        "asset_name": "Nvidia",
        "description": "Nvidia is a semiconductor company leading in GPU computing, AI acceleration hardware, and high performance data center infrastructure.",
        "asset_type": "web2",
        "category": "Semiconductors",
        "raw_sentiment": 0.46,
        "fear_greed_score": 74,
        "confidence_score": 0.86,
        "trend_1h": -0.01,
        "trend_24h": -0.24,
        "trend_7d": -6.4,
        "price_usd": 890.74,
        "market_cap_usd": 589586356959,
        "pe_ratio": 70.07,
        "avg_volume_24h_usd": 1008107724,
        "topic": "Margins",
        "is_high_confidence": false,
        "observed_at": "2026-01-29T18:34:00Z"
    },
    {
        "id": "sig_2009",
        "asset_symbol": "NVDA",
        "asset_name": "Nvidia",
        "description": "Nvidia is a semiconductor company leading in GPU computing, AI acceleration hardware, and high performance data center infrastructure.",
        "asset_type": "web2",
        "category": "Semiconductors",
        "raw_sentiment": -0.61,
        "fear_greed_score": 83,
        "confidence_score": 0.88,
        "trend_1h": 0.71,
        "trend_24h": 3.2,
        "trend_7d": 4.37,
        "price_usd": 566.25,
        "market_cap_usd": 3288961520585,
        "pe_ratio": 27.0,
        "avg_volume_24h_usd": 1383984368,
        "topic": "AI Growth",
        "is_high_confidence": false,
        "observed_at": "2025-12-26T01:20:00Z"
    },
    {
        "id": "sig_1010",
        "asset_symbol": "SOL",
        "asset_name": "Solana",
        "description": "Solana is a high performance Layer 1 blockchain optimized for fast transactions, low fees, and scalable decentralized applications.",
        "asset_type": "web3",
        "category": "L1",
        "raw_sentiment": 0.28,
        "fear_greed_score": 88,
        "confidence_score": 0.8,
        "trend_1h": 0.62,
        "trend_24h": 6.28,
        "trend_7d": 14.92,
        "price_usd": 14320.37,
        "tvl_usd": 56153075579,
        "pool_volume_24h_usd": 5949940810,
        "onchain_tx_growth_24h": 10.65,
        "topic": "Staking",
        "is_high_confidence": true,
        "observed_at": "2026-02-08T06:42:00Z"
    },
    {
        "id": "sig_1011",
        "asset_symbol": "SOL",
        "asset_name": "Solana",
        "description": "Solana is a high performance Layer 1 blockchain optimized for fast transactions, low fees, and scalable decentralized applications.",
        "asset_type": "web3",
        "category": "L1",
        "raw_sentiment": 0.39,
        "fear_greed_score": 83,
        "confidence_score": 0.9,
        "trend_1h": -1.05,
        "trend_24h": 4.02,
        "trend_7d": 2.66,
        "price_usd": 33713.08,
        "tvl_usd": 38065812084,
        "pool_volume_24h_usd": 13478169940,
        "onchain_tx_growth_24h": 2.57,
        "topic": "Usage",
        "is_high_confidence": false,
        "observed_at": "2026-01-05T20:35:00Z"
    },
    {
        "id": "sig_2012",
        "asset_symbol": "NVDA",
        "asset_name": "Nvidia",
        "description": "Nvidia is a semiconductor company leading in GPU computing, AI acceleration hardware, and high performance data center infrastructure.",
        "asset_type": "web2",
        "category": "Semiconductors",
        "raw_sentiment": -0.45,
        "fear_greed_score": 70,
        "confidence_score": 0.91,
        "trend_1h": 0.68,
        "trend_24h": 0.36,
        "trend_7d": 1.72,
        "price_usd": 687.72,
        "market_cap_usd": 1280542567404,
        "pe_ratio": 36.87,
        "avg_volume_24h_usd": 3273598497,
        "topic": "Innovation",
        "is_high_confidence": false,
        "observed_at": "2025-12-21T05:53:00Z"
    },
    {
        "id": "sig_1013",
        "asset_symbol": "BTC",
        "asset_name": "Bitcoin",
        "description": "Bitcoin is a decentralized Layer 1 blockchain and digital store of value widely used as a hedge against inflation and macro uncertainty.",
        "asset_type": "web3",
        "category": "L1",
        "raw_sentiment": -0.39,
        "fear_greed_score": 76,
        "confidence_score": 0.76,
        "trend_1h": 1.63,
        "trend_24h": 6.85,
        "trend_7d": 13.19,
        "price_usd": 37486.14,
        "tvl_usd": 20740378471,
        "pool_volume_24h_usd": 1138971378,
        "onchain_tx_growth_24h": 1.99,
        "topic": "Liquidity",
        "is_high_confidence": false,
        "observed_at": "2025-12-05T07:09:00Z"
    },
    {
        "id": "sig_1014",
        "asset_symbol": "ETH",
        "asset_name": "Ethereum",
        "description": "Ethereum is a programmable Layer 1 blockchain powering smart contracts, DeFi, NFTs, and decentralized applications.",
        "asset_type": "web3",
        "category": "L1",
        "raw_sentiment": -0.34,
        "fear_greed_score": 45,
        "confidence_score": 0.77,
        "trend_1h": -0.46,
        "trend_24h": 5.45,
        "trend_7d": 16.43,
        "price_usd": 18257.26,
        "tvl_usd": 31717768166,
        "pool_volume_24h_usd": 14515371923,
        "onchain_tx_growth_24h": 10.32,
        "topic": "Liquidity",
        "is_high_confidence": false,
        "observed_at": "2025-12-03T05:04:00Z"
    },
    {
        "id": "sig_1015",
        "asset_symbol": "ETH",
        "asset_name": "Ethereum",
        "description": "Ethereum is a programmable Layer 1 blockchain powering smart contracts, DeFi, NFTs, and decentralized applications.",
        "asset_type": "web3",
        "category": "L1",
        "raw_sentiment": -0.77,
        "fear_greed_score": 20,
        "confidence_score": 0.85,
        "trend_1h": 0.47,
        "trend_24h": 5.51,
        "trend_7d": 8.55,
        "price_usd": 62792.8,
        "tvl_usd": 68097129604,
        "pool_volume_24h_usd": 28997554155,
        "onchain_tx_growth_24h": 9.46,
        "topic": "Usage",
        "is_high_confidence": false,
        "observed_at": "2025-12-12T17:44:00Z"
    },
    {
        "id": "sig_2016",
        "asset_symbol": "TSLA",
        "asset_name": "Tesla",
        "description": "Tesla is an electric vehicle and clean energy company focused on EV manufacturing, battery innovation, and autonomous driving technology.",
        "asset_type": "web2",
        "category": "EV",
        "raw_sentiment": -0.28,
        "fear_greed_score": 25,
        "confidence_score": 0.84,
        "trend_1h": -0.53,
        "trend_24h": 0.91,
        "trend_7d": 8.81,
        "price_usd": 490.77,
        "market_cap_usd": 1779248453154,
        "pe_ratio": 10.99,
        "avg_volume_24h_usd": 13663166698,
        "topic": "Margins",
        "is_high_confidence": true,
        "observed_at": "2026-01-28T04:20:00Z"
    },
    {
        "id": "sig_2017",
        "asset_symbol": "NVDA",
        "asset_name": "Nvidia",
        "description": "Nvidia is a semiconductor company leading in GPU computing, AI acceleration hardware, and high performance data center infrastructure.",
        "asset_type": "web2",
        "category": "Semiconductors",
        "raw_sentiment": 0.13,
        "fear_greed_score": 90,
        "confidence_score": 0.89,
        "trend_1h": -0.16,
        "trend_24h": 0.01,
        "trend_7d": -2.06,
        "price_usd": 739.54,
        "market_cap_usd": 1736929549973,
        "pe_ratio": 46.02,
        "avg_volume_24h_usd": 11399957154,
        "topic": "AI Growth",
        "is_high_confidence": true,
        "observed_at": "2025-12-27T20:35:00Z"
    },
    {
        "id": "sig_2018",
        "asset_symbol": "AAPL",
        "asset_name": "Apple Inc",
        "description": "Apple Inc is a global consumer technology company generating revenue from hardware devices, digital services, and ecosystem subscriptions.",
        "asset_type": "web2",
        "category": "Tech",
        "raw_sentiment": 0.76,
        "fear_greed_score": 30,
        "confidence_score": 0.91,
        "trend_1h": -0.05,
        "trend_24h": 0.95,
        "trend_7d": -1.04,
        "price_usd": 266.88,
        "market_cap_usd": 2862423580572,
        "pe_ratio": 78.77,
        "avg_volume_24h_usd": 6388463698,
        "topic": "Innovation",
        "is_high_confidence": true,
        "observed_at": "2026-01-12T14:02:00Z"
    },
    {
        "id": "sig_2019",
        "asset_symbol": "AMZN",
        "asset_name": "Amazon",
        "description": "Amazon is a global ecommerce and cloud infrastructure company generating revenue from online retail, logistics, and AWS cloud services.",
        "asset_type": "web2",
        "category": "Ecommerce Cloud",
        "raw_sentiment": -0.16,
        "fear_greed_score": 22,
        "confidence_score": 0.88,
        "trend_1h": 0.61,
        "trend_24h": -1.37,
        "trend_7d": 3.49,
        "price_usd": 368.7,
        "market_cap_usd": 2109022615204,
        "pe_ratio": 73.76,
        "avg_volume_24h_usd": 2256419158,
        "topic": "Earnings",
        "is_high_confidence": false,
        "observed_at": "2026-01-16T06:08:00Z"
    },
    {
        "id": "sig_1020",
        "asset_symbol": "UNI",
        "asset_name": "Uniswap",
        "description": "Uniswap is a decentralized exchange protocol enabling permissionless token swaps and automated liquidity provision on blockchain networks.",
        "asset_type": "web3",
        "category": "DeFi",
        "raw_sentiment": 0.4,
        "fear_greed_score": 13,
        "confidence_score": 0.85,
        "trend_1h": 0.26,
        "trend_24h": -0.05,
        "trend_7d": -6.86,
        "price_usd": 62781.81,
        "tvl_usd": 63980803812,
        "pool_volume_24h_usd": 17774295971,
        "onchain_tx_growth_24h": -2.3,
        "topic": "Hype",
        "is_high_confidence": false,
        "observed_at": "2025-12-17T15:37:00Z"
    },
    {
        "id": "sig_1021",
        "asset_symbol": "UNI",
        "asset_name": "Uniswap",
        "description": "Uniswap is a decentralized exchange protocol enabling permissionless token swaps and automated liquidity provision on blockchain networks.",
        "asset_type": "web3",
        "category": "DeFi",
        "raw_sentiment": 0.44,
        "fear_greed_score": 34,
        "confidence_score": 0.81,
        "trend_1h": -1.93,
        "trend_24h": 1.92,
        "trend_7d": 2.95,
        "price_usd": 43632.05,
        "tvl_usd": 28201609426,
        "pool_volume_24h_usd": 8354938427,
        "onchain_tx_growth_24h": -3.0,
        "topic": "Hype",
        "is_high_confidence": false,
        "observed_at": "2025-12-21T18:30:00Z"
    },
    {
        "id": "sig_2022",
        "asset_symbol": "AAPL",
        "asset_name": "Apple Inc",
        "description": "Apple Inc is a global consumer technology company generating revenue from hardware devices, digital services, and ecosystem subscriptions.",
        "asset_type": "web2",
        "category": "Tech",
        "raw_sentiment": 0.61,
        "fear_greed_score": 55,
        "confidence_score": 0.81,
        "trend_1h": 1.41,
        "trend_24h": -1.3,
        "trend_7d": -1.28,
        "price_usd": 406.59,
        "market_cap_usd": 1676898432366,
        "pe_ratio": 39.63,
        "avg_volume_24h_usd": 13655132829,
        "topic": "Cloud",
        "is_high_confidence": false,
        "observed_at": "2025-12-25T06:36:00Z"
    }
];
