
export interface Asset {
    id: string;
    asset_symbol: string;
    asset_name: string;
    description: string;
    asset_type: "web3" | "web2";
    category: string;
    raw_sentiment: number;
    fear_greed_score: number;
    confidence_score: number;
    trend_1h: number;
    trend_24h: number;
    trend_7d: number;
    price_usd: number;
    tvl_usd?: number;
    market_cap_usd?: number;
    pool_volume_24h_usd?: number;
    avg_volume_24h_usd?: number;
    onchain_tx_growth_24h?: number;
    pe_ratio?: number;
    topic: string;
    is_high_confidence: boolean;
    observed_at: string;
}

export const ASSETS: Asset[] = [
    {
        id: "sig_1001",
        asset_symbol: "BTC",
        asset_name: "Bitcoin",
        description: "Bitcoin is a decentralized Layer 1 blockchain and digital store of value widely used as a hedge against inflation and macro uncertainty.",
        asset_type: "web3",
        category: "L1",
        raw_sentiment: 0.91,
        fear_greed_score: 90,
        confidence_score: 0.88,
        trend_1h: 0.4,
        trend_24h: 2.8,
        trend_7d: 7.2,
        price_usd: 68250,
        tvl_usd: 0,
        pool_volume_24h_usd: 28500000000,
        onchain_tx_growth_24h: 3.2,
        topic: "Momentum",
        is_high_confidence: true,
        observed_at: "2025-12-02T10:15:23Z",
    },
    {
        id: "sig_1002",
        asset_symbol: "ETH",
        asset_name: "Ethereum",
        description: "Ethereum is a programmable Layer 1 blockchain powering smart contracts, DeFi, NFTs, and decentralized applications.",
        asset_type: "web3",
        category: "L1",
        raw_sentiment: 0.62,
        fear_greed_score: 70,
        confidence_score: 0.84,
        trend_1h: 0.2,
        trend_24h: 1.9,
        trend_7d: 5.4,
        price_usd: 3820,
        tvl_usd: 68200000000,
        pool_volume_24h_usd: 15200000000,
        onchain_tx_growth_24h: 2.1,
        topic: "Staking",
        is_high_confidence: true,
        observed_at: "2025-12-02T10:17:23Z",
    },
    {
        id: "sig_1003",
        asset_symbol: "SOL",
        asset_name: "Solana",
        description: "Solana is a high performance Layer 1 blockchain optimized for fast transactions, low fees, and scalable decentralized applications.",
        asset_type: "web3",
        category: "L1",
        raw_sentiment: -0.45,
        fear_greed_score: 40,
        confidence_score: 0.79,
        trend_1h: -0.6,
        trend_24h: -1.2,
        trend_7d: 3.1,
        price_usd: 142,
        tvl_usd: 8200000000,
        pool_volume_24h_usd: 3200000000,
        onchain_tx_growth_24h: -0.5,
        topic: "Reliability",
        is_high_confidence: false,
        observed_at: "2025-12-02T10:20:23Z",
    },
    {
        id: "sig_1004",
        asset_symbol: "UNI",
        asset_name: "Uniswap",
        description: "Uniswap is a decentralized exchange protocol enabling permissionless token swaps and automated liquidity provision on blockchain networks.",
        asset_type: "web3",
        category: "DeFi",
        raw_sentiment: 0.55,
        fear_greed_score: 66,
        confidence_score: 0.81,
        trend_1h: 0.3,
        trend_24h: 2.2,
        trend_7d: 6.9,
        price_usd: 11.4,
        tvl_usd: 5400000000,
        pool_volume_24h_usd: 1800000000,
        onchain_tx_growth_24h: 4.4,
        topic: "Protocol Usage",
        is_high_confidence: false,
        observed_at: "2025-12-02T10:22:23Z",
    },
    {
        id: "sig_1005",
        asset_symbol: "DOGE",
        asset_name: "Dogecoin",
        description: "Dogecoin is a community driven meme cryptocurrency primarily used for tipping, payments, and speculative retail trading.",
        asset_type: "web3",
        category: "Meme",
        raw_sentiment: 0.94,
        fear_greed_score: 98,
        confidence_score: 0.75,
        trend_1h: 1.1,
        trend_24h: 6.4,
        trend_7d: 18.2,
        price_usd: 0.19,
        tvl_usd: 0,
        pool_volume_24h_usd: 2400000000,
        onchain_tx_growth_24h: 9.8,
        topic: "Hype",
        is_high_confidence: true,
        observed_at: "2025-12-02T10:25:23Z",
    },
    {
        id: "sig_2001",
        asset_symbol: "AAPL",
        asset_name: "Apple Inc",
        description: "Apple Inc is a global consumer technology company generating revenue from hardware devices, digital services, and ecosystem subscriptions.",
        asset_type: "web2",
        category: "Tech",
        raw_sentiment: 0.74,
        fear_greed_score: 75,
        confidence_score: 0.85,
        trend_1h: 0.1,
        trend_24h: 0.9,
        trend_7d: 3.5,
        price_usd: 212,
        market_cap_usd: 3300000000000,
        pe_ratio: 31.2,
        avg_volume_24h_usd: 8200000000,
        topic: "Services Growth",
        is_high_confidence: true,
        observed_at: "2025-12-02T10:30:23Z",
    },
    {
        id: "sig_2002",
        asset_symbol: "MSFT",
        asset_name: "Microsoft",
        description: "Microsoft is a global enterprise technology company focused on cloud computing, productivity software, enterprise infrastructure, and AI platforms.",
        asset_type: "web2",
        category: "Cloud",
        raw_sentiment: 0.82,
        fear_greed_score: 84,
        confidence_score: 0.9,
        trend_1h: 0.2,
        trend_24h: 1.4,
        trend_7d: 4.8,
        price_usd: 418,
        market_cap_usd: 3100000000000,
        pe_ratio: 35.6,
        avg_volume_24h_usd: 6400000000,
        topic: "Azure Growth",
        is_high_confidence: true,
        observed_at: "2025-12-02T10:32:23Z",
    },
    {
        id: "sig_2003",
        asset_symbol: "NVDA",
        asset_name: "Nvidia",
        description: "Nvidia is a semiconductor company leading in GPU computing, AI acceleration hardware, and high performance data center infrastructure.",
        asset_type: "web2",
        category: "Semiconductors",
        raw_sentiment: 0.9,
        fear_greed_score: 92,
        confidence_score: 0.88,
        trend_1h: 0.6,
        trend_24h: 3.2,
        trend_7d: 9.5,
        price_usd: 812,
        market_cap_usd: 2000000000000,
        pe_ratio: 58.3,
        avg_volume_24h_usd: 12000000000,
        topic: "AI Chips",
        is_high_confidence: true,
        observed_at: "2025-12-02T10:35:23Z",
    },
    {
        id: "sig_2004",
        asset_symbol: "AMZN",
        asset_name: "Amazon",
        description: "Amazon is a global ecommerce and cloud infrastructure company generating revenue from online retail, logistics, and AWS cloud services.",
        asset_type: "web2",
        category: "Ecommerce Cloud",
        raw_sentiment: 0.63,
        fear_greed_score: 68,
        confidence_score: 0.8,
        trend_1h: 0.15,
        trend_24h: 1.1,
        trend_7d: 3.9,
        price_usd: 185,
        market_cap_usd: 1900000000000,
        pe_ratio: 47.5,
        avg_volume_24h_usd: 7200000000,
        topic: "AWS Margins",
        is_high_confidence: false,
        observed_at: "2025-12-02T10:38:23Z",
    },
    {
        id: "sig_2005",
        asset_symbol: "TSLA",
        asset_name: "Tesla",
        description: "Tesla is an electric vehicle and clean energy company focused on EV manufacturing, battery innovation, and autonomous driving technology.",
        asset_type: "web2",
        category: "EV",
        raw_sentiment: 0.52,
        fear_greed_score: 60,
        confidence_score: 0.78,
        trend_1h: -0.2,
        trend_24h: 0.6,
        trend_7d: 2.2,
        price_usd: 268,
        market_cap_usd: 850000000000,
        pe_ratio: 68.1,
        avg_volume_24h_usd: 10500000000,
        topic: "Battery Innovation",
        is_high_confidence: false,
        observed_at: "2025-12-02T10:40:23Z",
    },
];
